version: '3.4'

services:
  apidocker:
    image: apidocker:dev
    container_name: ApiDocker
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "ApiDocker"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_apidocker$
    volumes:
      - C:\Users\pablo\Desktop\ApiDocker\ApiDocker\ApiDocker:/app
      - C:\Users\pablo\Desktop\ApiDocker\ApiDocker:/src
      - C:\Users\pablo\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_apidocker$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_apidocker$ \"/app/bin/Debug/net5.0/ApiDocker.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true